package com.viizfo.navgraphexample

import android.os.Bundle
import androidx.fragment.app.Fragment
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.appcompat.app.ActionBar
import androidx.appcompat.app.AppCompatActivity
import androidx.navigation.NavController
import androidx.navigation.fragment.findNavController
import com.viizfo.navgraphexample.databinding.FragmentLoginBinding


class LoginFragment : Fragment() {

    private lateinit var binding:FragmentLoginBinding

    private lateinit var navController:NavController

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {

        val activity = context as AppCompatActivity

        val actionBar: ActionBar? = activity.supportActionBar
        actionBar?.hide()

        // Inflate the layout for this fragment
        binding = FragmentLoginBinding.inflate(inflater,container,false)
        return binding.root
    }

    //In this function view is R.layout.fragment_login
    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        //We obtain the NavController through findNavigation
        //navController is  defined as member variable of the fragment
        navController = findNavController()

        binding.btnLoginNext.setOnClickListener{
            //Navigates to InfoFragment

            //Get info from UI EditText
            val login = Login()
            login.usr = binding.etUser.text.toString()
            login.pass = binding.etPass.text.toString()

            //Creating the action object
            val action = LoginFragmentDirections //This class is autogenerated with safeargs plugin
                .actionLoginFragmentToInfoFragment(login)
            //navController.navigate(R.id.action_loginFragment_to_infoFragment)
            //replace by:
            navController.navigate(action)
        }
    }
}